import { scoped } from 'command-bus'

const INTENT = scoped('INTENT/')

export const INTENTS = {
  /* pomodoro timer */
  POMODORO_TIMER_START: INTENT<{ todoId: string | number }>('POMODORO_TIMER_START'),
  POMODORO_TIMER_PAUSE: INTENT('POMODORO_TIMER_PAUSE'),
  POMODORO_TIMER_RESUME: INTENT('POMODORO_TIMER_RESUME'),
  POMODORO_TIMER_SKIP: INTENT('POMODORO_TIMER_SKIP'),
  POMODORO_TIMER_RESET: INTENT('RESET'),
  /* toods form  */
  INPUT_NEW_TODO_CONTENT: INTENT<string>('INPUT_NEW_TODO_CONTENT'),
  INPUT_ENDIT_TODO_CONTENT: INTENT<{ id: number, content: string }>('INPUT_ENDIT_TODO_CONTENT'),
  SHOW_TODO_EDIT_FORM: INTENT<{ id: number, content: string }>('SHOW_TODO_EDIT_FORM'),
  CLOSE_TODO_EDIT_FORM: INTENT('CLOSE_TODO_EDIT_FORM'),
  /* todos crud */
  ADD_TODO: INTENT<{ content: string }>('ADD_TODO'),
  UPDATE_TODO: INTENT<{ id: number, content: string }>('UPDATE_TODO'),
  DELETE_TODO: INTENT<{ id: number }>('DELETE_TODO'),
  TOGGLE_TODO_COMPLETION: INTENT<{ id: number }>('COMPLETE_TODO'),
  CLEAN_COMPLETED_TODOS: INTENT('CLEAN_COMPLETED_TODOS'),
}

export default INTENTS
